import type { IRDocument } from '../../types/ir';

export const simpleFixture: IRDocument = {
  version: '1.0.0',
  project_name: 'Simple Test',
  created_at: '2024-01-01T00:00:00.000Z',
  modified_at: '2024-01-01T00:00:00.000Z',
  root: {
    id: 'root-1',
    type: 'Frame',
    name: 'main_frame',
    abstract_props: { label: '', enabled: true, visible: true },
    geometry: { x: 0, y: 0, w: 800, h: 600 },
    style: { bg: '#1e1e2e', border_width: 0 },
    events: [],
    children: [
      {
        id: 'btn-1',
        parent: 'root-1',
        type: 'Button',
        name: 'start_btn',
        abstract_props: { label: 'Start', enabled: true, visible: true },
        geometry: { x: 20, y: 20, w: 100, h: 32 },
        style: { bg: '#89b4fa', fg: '#1e1e2e', font_family: 'Inter', font_size: 12 },
        events: [],
        children: [],
      },
      {
        id: 'lbl-1',
        parent: 'root-1',
        type: 'Label',
        name: 'status_lbl',
        abstract_props: { label: 'Ready', enabled: true, visible: true },
        geometry: { x: 140, y: 20, w: 200, h: 32 },
        style: { fg: '#cdd6f4', font_family: 'Inter', font_size: 11 },
        events: [],
        children: [],
      },
    ],
  },
  state_variables: [],
  instruments: [],
  data_loggers: [],
  alarms: [],
  settings: {
    window_title: 'Test Window',
    window_width: 800,
    window_height: 600,
    theme: 'clam',
  },
};

export const complexFixture: IRDocument = {
  version: '1.0.0',
  project_name: 'Complex Test',
  created_at: '2024-01-01T00:00:00.000Z',
  modified_at: '2024-01-01T00:00:00.000Z',
  root: {
    id: 'root-2',
    type: 'Frame',
    name: 'main_frame',
    abstract_props: { label: '', enabled: true, visible: true },
    geometry: { x: 0, y: 0, w: 1024, h: 768 },
    style: { bg: '#1e1e2e', border_width: 0 },
    events: [],
    children: [
      {
        id: 'entry-1',
        parent: 'root-2',
        type: 'Entry',
        name: 'voltage_entry',
        abstract_props: { label: 'Voltage', enabled: true, visible: true },
        geometry: { x: 10, y: 10, w: 120, h: 28 },
        style: {},
        widget_props: { textvariable: 'voltage_var' },
        events: [],
        children: [],
      },
      {
        id: 'scale-1',
        parent: 'root-2',
        type: 'Scale',
        name: 'gain_scale',
        abstract_props: { label: 'Gain', enabled: true, visible: true },
        geometry: { x: 10, y: 50, w: 200, h: 40 },
        style: {},
        widget_props: { from: 0, to: 100, orient: 'horizontal' },
        events: [],
        children: [],
      },
      {
        id: 'chk-1',
        parent: 'root-2',
        type: 'Checkbutton',
        name: 'enable_chk',
        abstract_props: { label: 'Enable Output', enabled: true, visible: true },
        geometry: { x: 10, y: 100, w: 140, h: 28 },
        style: {},
        widget_props: { variable: 'output_en' },
        events: [],
        children: [],
      },
      {
        id: 'btn-2',
        parent: 'root-2',
        type: 'Button',
        name: 'read_btn',
        abstract_props: { label: 'Read', enabled: true, visible: true },
        geometry: { x: 10, y: 140, w: 80, h: 32 },
        style: {},
        events: [
          { name: 'on_click', inline_code: 'val = self.multimeter.query("MEAS:VOLT:DC?")\nself.voltage_var.set(float(val))' },
        ],
        children: [],
      },
    ],
  },
  state_variables: [
    { id: 'sv-1', name: 'voltage_var', type: 'float', default_value: 0.0 },
    { id: 'sv-2', name: 'output_en', type: 'bool', default_value: false },
  ],
  instruments: [
    { id: 'inst-1', name: 'multimeter', protocol: 'visa', config: { resource_string: 'GPIB0::22::INSTR' }, commands: [] },
  ],
  data_loggers: [
    { id: 'dl-1', sources: ['voltage_var'], format: 'csv', interval_ms: 1000, path: './logs', max_file_size_mb: 50, enabled: true },
  ],
  alarms: [
    { id: 'al-1', source: 'voltage_var', max: 10.0, hysteresis: 0.5, action: 'visual', enabled: true },
  ],
  settings: {
    window_title: 'Lab Dashboard',
    window_width: 1024,
    window_height: 768,
    theme: 'clam',
  },
};
