import { describe, it, expect } from 'vitest';
import { generateTkinterCode } from '../tkinterGenerator';
import { simpleFixture, complexFixture } from './fixtures';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const goldenDir = join(__dirname, 'golden');

function goldenPath(name: string): string {
  return join(goldenDir, `${name}.py`);
}

function readGolden(name: string): string {
  return readFileSync(goldenPath(name), 'utf-8');
}

function writeGolden(name: string, content: string): void {
  if (!existsSync(goldenDir)) {
    mkdirSync(goldenDir, { recursive: true });
  }
  writeFileSync(goldenPath(name), content, 'utf-8');
}

const UPDATE_GOLDEN = process.env.UPDATE_GOLDEN === '1';

function normalizeCode(code: string): string {
  // Replace dynamic timestamps with a fixed placeholder
  return code.replace(
    /Generated by LabGUI Builder on \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z/,
    'Generated by LabGUI Builder on <TIMESTAMP>'
  );
}

describe('tkinterGenerator golden files', () => {
  it('generates simple fixture correctly', () => {
    const code = generateTkinterCode(simpleFixture);

    const normalized = normalizeCode(code);

    if (UPDATE_GOLDEN) {
      writeGolden('simple', normalized);
    }

    // Validate syntax
    expect(code).toContain('import tkinter as tk');
    expect(code).toContain('class Simple_TestApp:');
    expect(code).toContain('self.start_btn = tk.Button(');
    expect(code).toContain('self.status_lbl = tk.Label(');

    if (!UPDATE_GOLDEN) {
      expect(normalized).toBe(readGolden('simple'));
    }
  });

  it('generates complex fixture correctly', () => {
    const code = generateTkinterCode(complexFixture);

    const normalized = normalizeCode(code);

    if (UPDATE_GOLDEN) {
      writeGolden('complex', normalized);
    }

    // Validate syntax and structure
    expect(code).toContain('import tkinter as tk');
    expect(code).toContain('import pyvisa');
    expect(code).toContain('import threading');
    expect(code).toContain('import time');
    expect(code).toContain('import datetime');
    expect(code).toContain('import csv');
    expect(code).toContain('import pathlib');
    expect(code).toContain('class Complex_TestApp:');
    expect(code).toContain('class DataLogger:');
    expect(code).toContain('class AlarmMonitor:');
    expect(code).toContain('self.voltage_var = tk.DoubleVar(value=0)');
    expect(code).toContain('self.output_en = tk.BooleanVar(value=False)');
    expect(code).toContain('self.multimeter = self.rm.open_resource("GPIB0::22::INSTR")');
    expect(code).toContain('def _on_read_btn_click(self):');

    if (!UPDATE_GOLDEN) {
      expect(normalized).toBe(readGolden('complex'));
    }
  });
});

describe('tkinterGenerator Python syntax', () => {
  it('simple output is valid Python-like structure', () => {
    const code = generateTkinterCode(simpleFixture);
    // Basic checks that would catch obvious syntax issues
    const lines = code.split('\n');
    let indentLevel = 0;
    for (const line of lines) {
      if (!line.trim()) continue;
      const leading = line.match(/^(\s*)/)?.[1] ?? '';
      const spaces = leading.length;
      // Should be multiples of 4
      expect(spaces % 4).toBe(0);
      // Indent should not jump more than 4 spaces at a time
      if (spaces > indentLevel) {
        expect(spaces - indentLevel).toBeLessThanOrEqual(4);
      }
      indentLevel = spaces;
    }
  });
});
