"""
Auto-generated tkinter GUI — Complex Test
Generated by LabGUI Builder on <TIMESTAMP>
"""

import tkinter as tk
from tkinter import ttk
import threading
import time
import datetime
import csv
import pathlib
import pyvisa


class DataLogger:
    """Threaded CSV data logger with rotation."""
    def __init__(self, app, sources, path="./logs/", interval_ms=1000, max_file_size_mb=100):
        self.app = app
        self.sources = sources
        self.path = pathlib.Path(path)
        self.path.mkdir(parents=True, exist_ok=True)
        self.interval = interval_ms / 1000.0
        self.max_size = max_file_size_mb * 1024 * 1024
        self._running = False
        self._thread = None
        self._file = None
        self._writer = None
        self._file_index = 0

    def _open_file(self):
        if self._file:
            self._file.close()
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = self.path / f"log_{timestamp}_{self._file_index:03d}.csv"
        self._file = open(filename, "w", newline="")
        self._writer = csv.writer(self._file)
        self._writer.writerow(["timestamp"] + self.sources)
        self._file_index += 1

    def _loop(self):
        self._open_file()
        while self._running:
            time.sleep(self.interval)
            if not self._running:
                break
            row = [datetime.datetime.now().isoformat()]
            for src in self.sources:
                val = getattr(self.app, src, None)
                if hasattr(val, "get"):
                    row.append(val.get())
                else:
                    row.append(val)
            self._writer.writerow(row)
            self._file.flush()
            if self._file.tell() > self.max_size:
                self._open_file()

    def start(self):
        self._running = True
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()

    def stop(self):
        self._running = False
        if self._thread:
            self._thread.join(timeout=2.0)
        if self._file:
            self._file.close()



class AlarmMonitor:
    """Threaded alarm threshold monitor with hysteresis."""
    def __init__(self, app, source, min_val=None, max_val=None, hysteresis=1.0, action="visual"):
        self.app = app
        self.source = source
        self.min_val = min_val
        self.max_val = max_val
        self.hysteresis = hysteresis
        self.action = action
        self._running = False
        self._thread = None
        self._state = "normal"  # normal, alarm

    def _read(self):
        val = getattr(self.app, self.source, None)
        if hasattr(val, "get"):
            return val.get()
        return val

    def _check(self, value):
        if self._state == "normal":
            if (self.min_val is not None and value < self.min_val) or (self.max_val is not None and value > self.max_val):
                return "alarm"
        else:
            if (self.min_val is not None and value > self.min_val + self.hysteresis) and (self.max_val is not None and value < self.max_val - self.hysteresis):
                return "normal"
            if self.min_val is None and self.max_val is not None and value < self.max_val - self.hysteresis:
                return "normal"
            if self.max_val is None and self.min_val is not None and value > self.min_val + self.hysteresis:
                return "normal"
        return self._state

    def _loop(self):
        while self._running:
            time.sleep(0.5)
            if not self._running:
                break
            try:
                value = self._read()
                new_state = self._check(value)
                if new_state != self._state:
                    self._state = new_state
                    self.app.root.after(0, lambda: self._trigger(new_state, value))
            except Exception:
                pass

    def _trigger(self, state, value):
        if state == "alarm":
            print(f"[ALARM] {self.source} = {value} (min={self.min_val}, max={self.max_val})")
            if self.action == "visual":
                self.app.root.configure(bg="red")
            elif self.action == "audio":
                self.app.root.bell()
        else:
            print(f"[ALARM CLEARED] {self.source}")
            if self.action == "visual":
                self.app.root.configure(bg="")

    def start(self):
        self._running = True
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()

    def stop(self):
        self._running = False
        if self._thread:
            self._thread.join(timeout=2.0)



class Complex_TestApp:
    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title("Lab Dashboard")
        self.root.geometry("1024x768")

        # Apply ttk theme
        self._style = ttk.Style()
        self._style.theme_use("clam")


        # State variables
        self.voltage_var = tk.DoubleVar(value=0)
        self.output_en = tk.BooleanVar(value=False)

        # Instrument connections
        self.rm = pyvisa.ResourceManager()
        # Instrument: multimeter
        self.multimeter = self.rm.open_resource("GPIB0::22::INSTR")

        # Data loggers
        self._data_loggers = []
        self.logger_dl_1 = DataLogger(
            self,
            sources=["voltage_var"],
            path="./logs",
            interval_ms=1000,
            max_file_size_mb=50
        )
        self.logger_dl_1.start()
        self._data_loggers.append(self.logger_dl_1)

        # Alarm monitors
        self._alarm_monitors = []
        self.alarm_al_1 = AlarmMonitor(
            self,
            source="voltage_var",
            max_val=10,
            hysteresis=0.5,
            action="visual"
        )
        self.alarm_al_1.start()
        self._alarm_monitors.append(self.alarm_al_1)

        # Build UI
        self.main_frame = tk.Frame(root, bg="#1e1e2e", bd=0)
        self.main_frame.place(x=0, y=0, width=1024, height=768)
        self.voltage_entry = tk.Entry(self.main_frame)
        self.voltage_entry.place(x=10, y=10, width=120, height=28)
        self.voltage_entry.config(textvariable=self.voltage_var)
        self.gain_scale = ttk.Scale(self.main_frame)
        self.gain_scale.place(x=10, y=50, width=200, height=40)
        self.gain_scale.config(from_=0, to=100, orient=tk.HORIZONTAL)
        self.enable_chk = tk.Checkbutton(self.main_frame)
        self.enable_chk.place(x=10, y=100, width=140, height=28)
        self.enable_chk.config(text="Enable Output")
        self.enable_chk.config(variable=self.output_en)
        self.read_btn = tk.Button(self.main_frame)
        self.read_btn.place(x=10, y=140, width=80, height=32)
        self.read_btn.config(text="Read")
        self.read_btn.config(command=self._on_read_btn_click)

    def _on_read_btn_click(self):
        """Read click handler."""
        val = self.multimeter.query("MEAS:VOLT:DC?")
        self.voltage_var.set(float(val))


    def cleanup(self):
        """Gracefully shutdown threads and close connections."""
        for logger in self._data_loggers:
            logger.stop()
        for alarm in self._alarm_monitors:
            alarm.stop()
        try: self.multimeter.close()
        except Exception: pass
        try: self.rm.close()
        except Exception: pass

    def run(self):
        try:
            self.root.mainloop()
        finally:
            self.cleanup()


if __name__ == "__main__":
    root = tk.Tk()
    app = Complex_TestApp(root)
    try:
        app.run()
    except KeyboardInterrupt:
        app.cleanup()
