"""
Auto-generated tkinter GUI — Simple Test
Generated by LabGUI Builder on <TIMESTAMP>
"""

import tkinter as tk
from tkinter import ttk


class Simple_TestApp:
    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title("Test Window")
        self.root.geometry("800x600")

        # Apply ttk theme
        self._style = ttk.Style()
        self._style.theme_use("clam")


        # Build UI
        self.main_frame = tk.Frame(root, bg="#1e1e2e", bd=0)
        self.main_frame.place(x=0, y=0, width=800, height=600)
        self.start_btn = tk.Button(self.main_frame, bg="#89b4fa", fg="#1e1e2e", font=("Inter", 12))
        self.start_btn.place(x=20, y=20, width=100, height=32)
        self.start_btn.config(text="Start")
        self.status_lbl = tk.Label(self.main_frame, fg="#cdd6f4", font=("Inter", 11))
        self.status_lbl.place(x=140, y=20, width=200, height=32)
        self.status_lbl.config(text="Ready")

    def run(self):
        self.root.mainloop()


if __name__ == "__main__":
    root = tk.Tk()
    app = Simple_TestApp(root)
    try:
        app.run()
    except KeyboardInterrupt:
        app.cleanup()
